-- MySQL Script generated by MySQL Workbench
-- Sat Nov 19 23:13:52 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema disabilitydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema disabilitydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `disabilitydb` DEFAULT CHARACTER SET utf8 ;
USE `disabilitydb` ;

-- -----------------------------------------------------
-- Table `disabilitydb`.`bothsexesstats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disabilitydb`.`bothsexesstats` ;

CREATE TABLE IF NOT EXISTS `disabilitydb`.`bothsexesstats` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Sex` TEXT NULL DEFAULT NULL,
  `County` TEXT NULL DEFAULT NULL,
  `Amount` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 85
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `disabilitydb`.`disabled_age_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disabilitydb`.`disabled_age_group` ;

CREATE TABLE IF NOT EXISTS `disabilitydb`.`disabled_age_group` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `GEOG_ID` TEXT NULL DEFAULT NULL,
  `AIRO_AI_ID` BIGINT(20) NULL DEFAULT NULL,
  `ED_Ward` TEXT NULL DEFAULT NULL,
  `ED_WARD_ID` TEXT NULL DEFAULT NULL,
  `County_UD` TEXT NULL DEFAULT NULL,
  `Country` TEXT NULL DEFAULT NULL,
  `Persons.with.a.disability.aged.0.14` BIGINT(20) NULL DEFAULT NULL,
  `Persons.with.a.disability.aged.15...44` BIGINT(20) NULL DEFAULT NULL,
  `Persons.with.a.disability.aged.25...44` BIGINT(20) NULL DEFAULT NULL,
  `Persons.with.a.disability.aged.45...64` BIGINT(20) NULL DEFAULT NULL,
  `Persons.with.a.disability.aged.65.Plus` BIGINT(20) NULL DEFAULT NULL,
  `Total.persons.with.a.disability` BIGINT(20) NULL DEFAULT NULL,
  `Total.Pop` BIGINT(20) NULL DEFAULT NULL,
  `X..Persons.with.a.disability.aged.0.14` DOUBLE NULL DEFAULT NULL,
  `X..Persons.with.a.disability.aged.15...44` DOUBLE NULL DEFAULT NULL,
  `X..Persons.with.a.disability.aged.25...44` DOUBLE NULL DEFAULT NULL,
  `X..Persons.with.a.disability.aged.45...64` DOUBLE NULL DEFAULT NULL,
  `X..Persons.with.a.disability.aged.65.Plus` DOUBLE NULL DEFAULT NULL,
  `X..Total.persons.with.a.disability` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 18489
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `disabilitydb`.`disabledsurvey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disabilitydb`.`disabledsurvey` ;

CREATE TABLE IF NOT EXISTS `disabilitydb`.`disabledsurvey` (
  `ID` INT(11) NOT NULL,
  `Sex` TEXT NULL DEFAULT NULL,
  `Category` TEXT NULL DEFAULT NULL,
  `County` TEXT NULL DEFAULT NULL,
  `Amount` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `disabilitydb`.`healthcentres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disabilitydb`.`healthcentres` ;

CREATE TABLE IF NOT EXISTS `disabilitydb`.`healthcentres` (
  `Category` VARCHAR(255) NULL DEFAULT NULL,
  `Service name` VARCHAR(255) NULL DEFAULT NULL,
  `Alternative name` VARCHAR(255) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `County` VARCHAR(255) NULL DEFAULT NULL,
  `long_xcord` DECIMAL(10,8) NULL DEFAULT NULL,
  `lat_ycord` DECIMAL(11,8) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `disabilitydb`.`sentimentanalysis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disabilitydb`.`sentimentanalysis` ;

CREATE TABLE IF NOT EXISTS `disabilitydb`.`sentimentanalysis` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tweets` TEXT NULL DEFAULT NULL,
  `emotion` TEXT NULL DEFAULT NULL,
  `polarity` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3400
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
